name: UnbreakableAnvils
version: '${version}'
main: club.aurorapvp.unbreakableanvils.UnbreakableAnvils
api-version: '1.19'
authors: [Villagers654]
description: Signs that can run commands
website: aurorapvp.club

commands:
  unbreakableanvils:
    description: UnbreakableAnvils commands
    permission: unbreakableanvils.admin
    aliases:
      - ua
permissions:
  unbreakableanvils.admin:
    description: Enables use of UnbreakableAnvils
    default: op